"""0.4.9 group 3: opened coffee-mix stick / freeze-dried doenjang & egg soup pouches.

Defects
- Contents seen from the top were 14 flat orange boxes (pixel-stepped slabs, procedural colour).
- doenjangblock_open / eggsoupblock_open: the pouch reuses the 0.044 m wide coffee-stick mesh while
  the print is a whole soup pouch (~0.67-0.76 w/h), so the print was squeezed ~2.5x horizontally;
  eggsoup's UV rectangle also cut off the left of the pack ("계" missing) and showed background.

Fix
- Remove the box contents (texture color(0.72,0.36,0.09)) in every visual LOD and build new ones
  from the pouch's own inner wall (cream faces) cross-section:
  * coffeemix_open: a slightly domed powder surface that fills the opening (+ a short skirt),
  * doenjang/egg: a chamfered freeze-dried block standing in the pouch (top + sides),
  textured with the new r049_opened_contents_co.paa (tools/models/textures/opened_contents,
  generated by tex_g3.py).
- doenjang/egg only: X scaled by 0.09/0.044 (width 0.044 -> 0.09 m; the closed pack is 0.10 m) in
  the visual and geometry LODs (memory points unchanged), and the print UVs re-cropped to the
  exact pack rectangle in batch02_37_DoenjangBlock_front_group_co.paa with the pouch's aspect
  (0.09 x 0.12): doenjang keeps the lower 213 px of its pack (the torn-off top loses a strip of the
  bowl photo), egg soup shows its whole pack.
coffeemix_open print is left as is (not part of the defect).
"""
import math
import g3common as g

TEX = r'KF_Pantry\data\r049_opened_contents_co.paa'
MAT = r'KF_Pantry\data\r043_food.rvmat'
PRINT = 'DoenjangBlock_front_group'
SCALE_X = 0.09 / 0.044
# pack rectangles in the 512 px group texture (pixels), chosen for w/h = 0.09 / 0.12
CROP = {'doenjangblock_open': (62, 49, 222, 262), 'eggsoupblock_open': (226, 22, 398, 251)}
QUAD = {'coffeemix_open': (0.0, 0.0), 'doenjangblock_open': (0.5, 0.0), 'eggsoupblock_open': (0.0, 0.5)}
SIDE_QUAD = (0.5, 0.5)


def inner_contour(lod, y, n=32):
    """Inner cross-section of the pouch near height y as n points (x, z), shrunk slightly."""
    pts = [lod['vertices'][c[0]] for f in lod['faces'] if g.tex_has(f, 'color(0.88,0.85,0.77')
           for c in f['corners']]
    pts = [p for p in pts if abs(p[1] - y) < 0.012]
    xs = max(abs(p[0]) for p in pts); zs = max(abs(p[2]) for p in pts)
    best = [None] * n
    for p in pts:
        a = math.atan2(p[2] / zs, p[0] / xs); r = math.hypot(p[0] / xs, p[2] / zs)
        k = int(round((a % (2 * math.pi)) / (2 * math.pi) * n)) % n
        best[k] = r if best[k] is None else min(best[k], r)
    for k in range(n):  # fill empty bins from neighbours
        if best[k] is None:
            j = 1
            while best[(k - j) % n] is None and best[(k + j) % n] is None:
                j += 1
            best[k] = best[(k - j) % n] if best[(k - j) % n] is not None else best[(k + j) % n]
    out = []
    for k in range(n):
        a = 2 * math.pi * k / n
        out.append((0.95 * best[k] * math.cos(a) * xs, 0.95 * best[k] * math.sin(a) * zs))
    return out, xs, zs


def planar_uv(quad, half_w):
    """(x, z) -> uv inside a 0.5 x 0.5 quadrant, x in [-half_w, half_w] -> 0.46 of u."""
    s = 0.46 / (2 * half_w)
    return lambda x, z: (quad[0] + 0.25 + x * s, quad[1] + 0.25 + z * s)


def add_powder(m, lod, y_top):
    ring, xs, zs = inner_contour(lod, y_top)
    uv = planar_uv(QUAD['coffeemix_open'], xs)
    n = len(ring)
    mid = [(0.6 * x, y_top + 0.0012 + 0.0004 * math.sin(3.1 * k), 0.6 * z) for k, (x, z) in enumerate(ring)]
    outer = [(x, y_top, z) for x, z in ring]
    ctr = (0.0, y_top + 0.0018, 0.0)
    new = []
    for k in range(n):
        a, b = outer[k], outer[(k + 1) % n]; c, d = mid[(k + 1) % n], mid[k]
        new.append(g.add_face_out(m, lod, [a, b, c, d], (0, 1, 0), TEX, MAT, [uv(p[0], p[2]) for p in (a, b, c, d)]))
        new.append(g.add_face_out(m, lod, [d, c, ctr], (0, 1, 0), TEX, MAT, [uv(p[0], p[2]) for p in (d, c, ctr)]))
    # short skirt so the powder does not look like a floating sheet at grazing angles
    for k in range(n):
        a, b = outer[k], outer[(k + 1) % n]
        a2, b2 = (a[0], a[1] - 0.012, a[2]), (b[0], b[1] - 0.012, b[2])
        o = g.unit((a[0] + b[0], 0, a[2] + b[2]))
        new.append(g.add_face_out(m, lod, [a, b, b2, a2], o, TEX, MAT,
                                  [uv(a[0], 0.0045), uv(b[0], 0.0045), uv(b[0], 0.0095), uv(a[0], 0.0095)]))
    g.recompute_normals(lod, new, angle=75)
    return len(new), dict(xs=round(xs, 4), zs=round(zs, 4))


def add_block(m, lod, name, y_top, height=0.026, bx=0.019, cham=0.0018):
    ring, xs, zs = inner_contour(lod, y_top)
    bz = min(0.0068, 0.92 * zs * math.sqrt(max(0.0, 1 - (bx / xs) ** 2)))
    c1, c2 = min(cham, bz * 0.45), cham
    poly = [(bx - c2, -bz), (bx, -bz + c1), (bx, bz - c1), (bx - c2, bz),
            (-bx + c2, bz), (-bx, bz - c1), (-bx, -bz + c1), (-bx + c2, -bz)]
    uvt = planar_uv(QUAD[name], bx * 1.05)
    new = []
    top = [(x, y_top, z) for x, z in poly]
    # top: fan from centre (quads/tris)
    ctr = (0.0, y_top, 0.0)
    for k in range(len(top)):
        a, b = top[k], top[(k + 1) % len(top)]
        new.append(g.add_face_out(m, lod, [a, b, ctr], (0, 1, 0), TEX, MAT, [uvt(p[0], p[2]) for p in (a, b, ctr)]))
    # sides: u = perimeter length, v = depth below the top, same texel density as the top
    s = 0.46 / (2 * bx * 1.05)
    per = 0.0
    for k in range(len(poly)):
        (x0, z0), (x1, z1) = poly[k], poly[(k + 1) % len(poly)]
        L = math.hypot(x1 - x0, z1 - z0)
        u0 = SIDE_QUAD[0] + 0.02 + (per * s) % 0.3; u1 = u0 + L * s
        v0 = SIDE_QUAD[1] + 0.02; v1 = v0 + height * s
        a, b = (x0, y_top, z0), (x1, y_top, z1)
        a2, b2 = (x0, y_top - height, z0), (x1, y_top - height, z1)
        o = g.unit((z1 - z0, 0.0, -(x1 - x0)))
        if o[0] * (x0 + x1) + o[2] * (z0 + z1) < 0:
            o = (-o[0], 0.0, -o[2])
        new.append(g.add_face_out(m, lod, [a, b, b2, a2], o, TEX, MAT, [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]))
        per += L
    g.recompute_normals(lod, new, angle=30)
    return len(new), dict(block_half=(bx, round(bz, 4)), inner_half=(round(xs, 4), round(zs, 4)))


def fix(name):
    m = g.load_original('KF_Pantry', name)
    info = {}
    if name in CROP:
        m.scale((SCALE_X, 1, 1), lods=[l for l in m.lods if l['resolution'] < 1e14])  # not the memory LOD
        x0, y0, x1, y1 = [p / 512 for p in CROP[name]]
        for lod in m.visual_lods():
            fs = g.faces_where(lod, lambda i, f: g.tex_has(f, PRINT))
            us = [c[2] for i in fs for c in lod['faces'][i]['corners']]
            vs = [c[3] for i in fs for c in lod['faces'][i]['corners']]
            ua, ub, va, vb = min(us), max(us), min(vs), max(vs)
            for i in fs:
                f = lod['faces'][i]
                f['corners'] = [(vi, ni, x0 + (u - ua) / (ub - ua) * (x1 - x0), y0 + (v - va) / (vb - va) * (y1 - y0))
                                for vi, ni, u, v in f['corners']]
            info['print_uv_lod%g' % lod['resolution']] = [[round(ua, 3), round(ub, 3)], [round(va, 3), round(vb, 3)],
                                                           '->', [round(x0, 4), round(x1, 4)], [round(y0, 4), round(y1, 4)]]
    for lod in m.visual_lods():
        removed = m.remove_faces(lod, lambda i, f: g.tex_has(f, 'color(0.72,0.36,0.09'))
        if name == 'coffeemix_open':
            added, extra = add_powder(m, lod, 0.105)
        else:
            added, extra = add_block(m, lod, name, 0.115)
        info['lod%g' % lod['resolution']] = dict(removed_box_faces=removed, added_faces=added, **extra)
    return m, info


def main():
    report = []
    for name in ('coffeemix_open', 'doenjangblock_open', 'eggsoupblock_open'):
        m, info = fix(name)
        g.save(m, 'KF_Pantry', name, report, **info)
    g.write_report('fix_opened_contents', report)


if __name__ == '__main__':
    main()
